export {
  PROTOCOL_VERSION,
  MAX_FORMULA_BYTES,
  MAX_ENVELOPE_BYTES,
  MAX_RESPONSE_BYTES,
  appendResponseChunk,
  decodeUtf8Strict,
  parseStrictJson,
} from "./bridge/protocol.js";

export type {
  MathematicalDomain,
  IndexDomain,
  VariableDeclaration,
  DomainConstraint,
  EquationRequest,
  FunctionDefinition,
  PrimitiveCost,
  Assumption,
  DirectedDefinition,
  ExactScenarioScalar,
  OptimizationObjectiveInput,
  AlgorithmicOptimizationFamily,
  OptimizationConfig,
  IntervalBound,
  Scenario,
  EquationTarget,
  DerivedTarget,
  PropertyCheckRequest,
  ExpressionQueryRequest,
  SystemQueryRequest,
  QueryRequest,
  ExpressionAnalysisRequest,
  SystemAnalysisRequest,
  AnalysisRequest,
  CandidateComputation,
  CandidateTarget,
  CandidateOutputMapping,
  CandidateComparisonRequest,
  DominanceRange,
  DominanceRequest,
  OptimizeRequest,
  FormulaRequest,
} from "./bridge/requests.js";

export type {
  Interpretation,
  OperationCounts,
  SymbolicOperationCounts,
  RelationshipUse,
  SourceLocation,
  SourceSpan,
  SourceReference,
  DirectWorkApplicability,
  EffectiveIndexDomain,
  ConstraintUse,
  EquationEffectiveDomains,
  EquationReport,
  ScenarioResult,
  SystemReport,
  OptimizationSuggestion,
  OptimizationCandidate,
  OptimizationObjective,
  OptimizationTraceStep,
  OptimizationPlan,
  OptimizationReport,
  AnalysisSuccess,
  ResolvedTarget,
  PropertyCheck,
  DerivedCandidate,
  QueryAnswer,
  QueryResult,
  AnalysisFailure,
  CandidateAnalysisSuccess,
  CandidateAnalysisReport,
  CandidateComparisonSuccess,
  DominanceTerm,
  DominanceCell,
  DominanceSuccess,
  OptimizationOperationSuccess,
  OptimizationOperationFailure,
  OptimizationOperationResult,
  BridgeResult,
} from "./bridge/results.js";

export { BridgeError } from "./bridge/diagnostics.js";
export type { BridgeFailureKind } from "./bridge/diagnostics.js";
export { invokeAdapter } from "./bridge/client.js";
