# pyright: reportPrivateUsage=false
from py_science.formula.contracts._base import (
    StructuredModel,
)
from py_science.formula.contracts.common import (
    _NAME_PATTERN as _NAME_PATTERN,
)
from py_science.formula.contracts.common import (
    MAX_ASSUMPTIONS,
    MAX_CHOICES_PER_VARIABLE,
    MAX_CONSTRAINTS_PER_EQUATION,
    MAX_DEFINITIONS,
    MAX_DOMAINS_PER_EQUATION,
    MAX_EQUATIONS,
    MAX_FORMULA_BYTES,
    MAX_FUNCTIONS,
    MAX_GENERATED_SCENARIO_RESULTS,
    MAX_NAME_LENGTH,
    MAX_PARAMETERS,
    MAX_PRIMITIVE_COSTS,
    MAX_SCENARIO_INTEGER_BITS,
    MAX_SCENARIOS,
    MAX_TREATMENTS_PER_SCENARIO,
    MAX_VARIABLES,
    Assumption,
    ConstraintUse,
    DerivedTarget,
    DirectedDefinition,
    DirectWorkApplicability,
    DomainConstraint,
    EffectiveIndexDomain,
    EquationEffectiveDomains,
    EquationRequest,
    EquationTarget,
    ExactScenarioScalar,
    ExpressionTarget,
    FormulaSyntax,
    FunctionDefinition,
    IndexDomain,
    Interpretation,
    IntervalBound,
    IntervalResult,
    MathematicalDomain,
    OperationCounts,
    PrimitiveCost,
    RelationshipUse,
    Scenario,
    SymbolicOperationCounts,
    VariableDeclaration,
)
from py_science.formula.contracts.common import (
    _exact_scenario_scalar as _exact_scenario_scalar,
)
from py_science.formula.contracts.common import (
    _require_unique as _require_unique,
)
from py_science.formula.contracts.common import (
    _validate_output_identities as _validate_output_identities,
)
from py_science.formula.contracts.common import (
    _validate_parameters as _validate_parameters,
)
from py_science.formula.contracts.comparison import (
    CandidateAnalysisReport,
    CandidateComparisonOutcome,
    CandidateComparisonRequest,
    CandidateComparisonSuccess,
    CandidateComputation,
    CandidateOutputComparison,
    CandidateOutputMapping,
    CandidateTargetReference,
    CandidateWorkComparison,
)
from py_science.formula.contracts.dominance import (
    DominanceAnalysisOutcome,
    DominanceAnalysisRequest,
    DominanceAnalysisSuccess,
    DominanceCell,
    DominanceEvidence,
    DominanceExclusion,
    DominanceIntegerRangeCell,
    DominanceIntervalCell,
    DominancePointCell,
    DominanceRange,
    DominanceTerm,
)
from py_science.formula.contracts.dominance import (
    _dominance_bounds_within as _dominance_bounds_within,
)
from py_science.formula.contracts.dominance import (
    _dominance_cell_bounds as _dominance_cell_bounds,
)
from py_science.formula.contracts.dominance import (
    _dominance_exact_sort_key as _dominance_exact_sort_key,
)
from py_science.formula.contracts.dominance import (
    _range_bounds as _range_bounds,
)
from py_science.formula.contracts.dominance import (
    _validate_complete_dominance_coverage as _validate_complete_dominance_coverage,
)
from py_science.formula.contracts.dominance import (
    _validate_dominance_cell_order as _validate_dominance_cell_order,
)
from py_science.formula.contracts.evidence import (
    AsymptoticEvidence,
    AsymptoticRemainder,
    BoundedQueryText,
    ClosedFormEvidence,
    CounterexampleEvidence,
    DerivedCandidate,
    IdentityEvidence,
    LimitEvidence,
    PropertyEvidence,
    QueryEvidence,
)
from py_science.formula.contracts.optimization import (
    OPTIMIZATION_FAMILY_TIERS,
    AlgorithmicOptimizationFamily,
    OptimizationCandidate,
    OptimizationConfig,
    OptimizationFailure,
    OptimizationIntermediate,
    OptimizationKind,
    OptimizationObjective,
    OptimizationOccurrence,
    OptimizationOrdering,
    OptimizationPlan,
    OptimizationReport,
    OptimizationSuccess,
    OptimizationSuggestion,
    OptimizationTarget,
    OptimizationTier,
    OptimizationTraceStep,
    OptimizationTransformation,
    OptimizeOutcome,
    UnitWorkObjective,
    WeightedOperationsObjective,
    WeightedOperationWeights,
)
from py_science.formula.contracts.optimization import (
    _validate_optimization_plan_population as _validate_optimization_plan_population,
)
from py_science.formula.contracts.queries import (
    AsymptoticQuery,
    AsymptoticResult,
    ClosedFormQuery,
    ClosedFormResult,
    EquivalenceQuery,
    EquivalenceResult,
    LimitQuery,
    LimitResult,
    PropertiesQuery,
    PropertiesResult,
    PropertyCheck,
    QueryAnswer,
    QueryBase,
    QueryRequest,
    QueryResult,
    QueryResultCommon,
    ResolvedTarget,
    SignPropertyCheck,
    VariablePropertyCheck,
)
from py_science.formula.contracts.queries import (
    _validate_query_answers as _validate_query_answers,
)
from py_science.formula.contracts.reports import (
    AnalysisError,
    AnalysisErrorCode,
    AnalysisFailure,
    AnalysisOutcome,
    AnalysisSuccess,
    EquationReport,
    ReuseReport,
    ScenarioResult,
    SourceLocation,
    SourceReference,
    SourceSpan,
    SystemReport,
)
from py_science.formula.contracts.reports import (
    _validate_direct_work_variant as _validate_direct_work_variant,
)
from py_science.formula.contracts.requests import (
    AnalysisRequest,
    OptimizeRequest,
)

__all__ = [
    "MAX_ASSUMPTIONS",
    "MAX_CHOICES_PER_VARIABLE",
    "MAX_CONSTRAINTS_PER_EQUATION",
    "MAX_DEFINITIONS",
    "MAX_DOMAINS_PER_EQUATION",
    "MAX_EQUATIONS",
    "MAX_FORMULA_BYTES",
    "MAX_FUNCTIONS",
    "MAX_GENERATED_SCENARIO_RESULTS",
    "MAX_NAME_LENGTH",
    "MAX_PARAMETERS",
    "MAX_PRIMITIVE_COSTS",
    "MAX_SCENARIOS",
    "MAX_SCENARIO_INTEGER_BITS",
    "MAX_TREATMENTS_PER_SCENARIO",
    "MAX_VARIABLES",
    "OPTIMIZATION_FAMILY_TIERS",
    "AlgorithmicOptimizationFamily",
    "AnalysisError",
    "AnalysisErrorCode",
    "AnalysisFailure",
    "AnalysisOutcome",
    "AnalysisRequest",
    "AnalysisSuccess",
    "Assumption",
    "AsymptoticEvidence",
    "AsymptoticQuery",
    "AsymptoticRemainder",
    "AsymptoticResult",
    "BoundedQueryText",
    "CandidateAnalysisReport",
    "CandidateComparisonOutcome",
    "CandidateComparisonRequest",
    "CandidateComparisonSuccess",
    "CandidateComputation",
    "CandidateOutputComparison",
    "CandidateOutputMapping",
    "CandidateTargetReference",
    "CandidateWorkComparison",
    "ClosedFormEvidence",
    "ClosedFormQuery",
    "ClosedFormResult",
    "ConstraintUse",
    "CounterexampleEvidence",
    "DerivedCandidate",
    "DerivedTarget",
    "DirectWorkApplicability",
    "DirectedDefinition",
    "DomainConstraint",
    "DominanceAnalysisOutcome",
    "DominanceAnalysisRequest",
    "DominanceAnalysisSuccess",
    "DominanceCell",
    "DominanceEvidence",
    "DominanceExclusion",
    "DominanceIntegerRangeCell",
    "DominanceIntervalCell",
    "DominancePointCell",
    "DominanceRange",
    "DominanceTerm",
    "EffectiveIndexDomain",
    "EquationEffectiveDomains",
    "EquationReport",
    "EquationRequest",
    "EquationTarget",
    "EquivalenceQuery",
    "EquivalenceResult",
    "ExactScenarioScalar",
    "ExpressionTarget",
    "FormulaSyntax",
    "FunctionDefinition",
    "IdentityEvidence",
    "IndexDomain",
    "Interpretation",
    "IntervalBound",
    "IntervalResult",
    "LimitEvidence",
    "LimitQuery",
    "LimitResult",
    "MathematicalDomain",
    "OperationCounts",
    "OptimizationCandidate",
    "OptimizationConfig",
    "OptimizationFailure",
    "OptimizationIntermediate",
    "OptimizationKind",
    "OptimizationObjective",
    "OptimizationOccurrence",
    "OptimizationOrdering",
    "OptimizationPlan",
    "OptimizationReport",
    "OptimizationSuccess",
    "OptimizationSuggestion",
    "OptimizationTarget",
    "OptimizationTier",
    "OptimizationTraceStep",
    "OptimizationTransformation",
    "OptimizeOutcome",
    "OptimizeRequest",
    "PrimitiveCost",
    "PropertiesQuery",
    "PropertiesResult",
    "PropertyCheck",
    "PropertyEvidence",
    "QueryAnswer",
    "QueryBase",
    "QueryEvidence",
    "QueryRequest",
    "QueryResult",
    "QueryResultCommon",
    "RelationshipUse",
    "ResolvedTarget",
    "ReuseReport",
    "Scenario",
    "ScenarioResult",
    "SignPropertyCheck",
    "SourceLocation",
    "SourceReference",
    "SourceSpan",
    "StructuredModel",
    "SymbolicOperationCounts",
    "SystemReport",
    "UnitWorkObjective",
    "VariableDeclaration",
    "VariablePropertyCheck",
    "WeightedOperationWeights",
    "WeightedOperationsObjective",
]
